`timescale 1ns/1ps
`define SIMULATION
module mult_32_TB;
    reg clk, rst, reset, start;
    reg [15:0] A, B;
    wire [31:0] PP;
    wire done; 
    mult_32 uut (.clk(clk),.B(in_B),.A(in_A),.rst(rst),.init(start),.PP(PP),.done(done));
    parameter PERIOD = 20;
    parameter real DUTY_CYCLE = 0.5;
    parameter OFFSET = 0;
    reg [20:0] i;
        event reset_trigger;
        event reset_done_trigger;
        initial begin
            forever begin
                @(reset_trigger);
                    @(negedge clk);
                    rst = 1;
                    @(negedge clk);
                    rst = 0;
                    -> reset_done_trigger;
            end
        end
    initial begin 
        clk = 0;
        rst = 1;
        start = 0;
        A = 16'h0005;
        B = 16'h0003;
    end
    initial begin 
        #OFFSET;
        forever begin
            clk = 1'b0;
            #(PERIOD-(PERIOD*DUTY_CYCLE)) clk = 1'b1;
            #(PERIOD*DUTY_CYCLE);
        end
    end
    initial begin 
      #10-> reset_trigger;
      @(reset_done_trigger);
      @(posedge clk);
      start = 0;
      @(posedge clk);
        start = 1;
      for (i = 0; i < 2; i = i + 1) begin
        @(posedge clk);
      end
      start = 0;
      for (i = 0; i < 17; i = i + 1) begin
        @(posedge clk);
      end
    end
    initial begin:TEST_CASE
        $dumpfile("mult_32_TB.vcd");
        $dumpvars(-1, uut);
        #((PERIOD*DUTY_CYCLE)*120) $finish;
        end
endmodule